"""
app/models/internal.py

Internal Pydantic models aligned to Flow.md's 3-tier data hierarchy.

Hierarchy
---------
  Category       — Display-only label for UI grouping (exactly 1 per session).
  Product Type   — Functional class of product (up to 10 per session).
  Product Item   — Real-world product listing from SERP (up to 10 per type).

These models are NEVER serialised directly into API responses — they are
intermediate data structures that services pass between each other.
For API-facing schemas, see responses.py.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


# ── 1. PRODUCT ITEM ──────────────────────────────────────────────────────────
#
# Represents a single real-world product listing retrieved from the SERP API.
# Product names are ALWAYS sourced from SERP — never AI-generated.
# ─────────────────────────────────────────────────────────────────────────────


class ProductItem(BaseModel):
    """
    A single real-world product listing fetched from SERP API.

    Required fields block card rendering if missing.
    Optional fields are shown when available and silently skipped when absent.
    """

    # Required fields — card will not render without these
    product_name: str = Field(..., description="Product name sourced from SERP — never AI-generated.")
    image_url: str = Field(default="", description="Product image URL for card display.")
    price_inr: str = Field(default="", description="Price in INR. Convert from source currency if needed.")
    short_description: str = Field(default="", description="From listing, or AI fallback if unavailable.")
    buy_link: str = Field(default="", description="Direct purchase link. Opens in a new tab.")

    # Optional fields — shown when available, silently skipped when absent
    rating: Optional[float] = Field(default=None, description="Numeric rating from SERP.")
    brand: Optional[str] = Field(default=None, description="Brand name from SERP.")
    reviews_count: Optional[int] = Field(default=None, description="Number of reviews from SERP.")
    delivery_info: Optional[str] = Field(default=None, description="Delivery information from SERP.")
    availability: Optional[str] = Field(default=None, description="Stock status, e.g. 'In Stock'.")
    source: Optional[str] = Field(default=None, description="Platform name, e.g. 'Amazon', 'Flipkart'.")

    @property
    def has_required_fields(self) -> bool:
        """True if all required fields for card rendering are present."""
        return bool(
            self.product_name
            and self.image_url
            and self.price_inr
            and self.buy_link
        )


# ── 2. PRODUCT TYPE ──────────────────────────────────────────────────────────
#
# A functional class of product the user actually needs (e.g. "Waterproof
# Trekking Shoes"). Each Product Type drives one SERP search query.
# ─────────────────────────────────────────────────────────────────────────────


class ProductType(BaseModel):
    """
    A functional class of product generated by AI at runtime.

    Each Product Type drives one SERP search query. The AI also generates
    a brief description explaining why this product type is relevant to
    the user's specific context.
    """

    product_type: str = Field(..., description="Functional class name, e.g. 'Waterproof Trekking Shoes'.")
    description: str = Field(
        default="",
        description="2-3 sentence description referencing the user's specific context.",
    )
    product_items: List[ProductItem] = Field(
        default_factory=list,
        description="Real product listings fetched from SERP for this type.",
    )
    serp_error: bool = Field(
        default=False,
        description="True when SERP retrieval failed for this product type.",
    )
    serp_error_message: Optional[str] = Field(
        default=None,
        description="User-facing error message when SERP fails.",
    )

    @property
    def has_sufficient_items(self) -> bool:
        """True if at least 5 valid product items are available for card rendering."""
        valid_count = sum(1 for item in self.product_items if item.has_required_fields)
        return valid_count >= 5

    @property
    def valid_items(self) -> List[ProductItem]:
        """Return only items with all required fields present."""
        return [item for item in self.product_items if item.has_required_fields]


# ── 3. RECOMMENDATION RESULT ─────────────────────────────────────────────────
#
# The complete output of the recommendation pipeline (Steps 5 + 6).
# Exactly 1 category + up to 10 product types + their SERP items.
# ─────────────────────────────────────────────────────────────────────────────


class RecommendationResult(BaseModel):
    """
    Complete output of the recommendation + SERP retrieval pipeline.

    This is what the orchestrator produces after Steps 5 and 6.
    """

    category: str = Field(
        default="Recommendations",
        description="Display-only label for UI grouping. Exactly 1 per session.",
    )
    product_types: List[ProductType] = Field(
        default_factory=list,
        description="Functional product classes, up to 10 per session.",
    )
    provider_used: Optional[str] = Field(
        default=None,
        description="Which LLM handled the recommendation step.",
    )

    @property
    def has_results(self) -> bool:
        """True if at least one product type has items."""
        return any(pt.product_items for pt in self.product_types)

    @property
    def all_serp_failed(self) -> bool:
        """True if SERP failed for every product type."""
        return all(pt.serp_error for pt in self.product_types) if self.product_types else True


# ── 4. QUESTION WITH OPTIONS ─────────────────────────────────────────────────
#
# Represents a follow-up question with optional selectable answer options.
# Used in the Question Engine (Step 3).
# ─────────────────────────────────────────────────────────────────────────────


class QuestionWithOptions(BaseModel):
    """A follow-up question with optional selectable answer options."""

    question: str = Field(..., description="The follow-up question text.")
    options: List[str] = Field(
        default_factory=list,
        description="Selectable answer options (pills). Empty if open-ended.",
    )


# ── 5. CLARIFICATION ROUND RESULT ────────────────────────────────────────────
#
# Result from the question engine for a specific round.
# ─────────────────────────────────────────────────────────────────────────────


class ClarificationRoundResult(BaseModel):
    """Result from generating questions for a specific round."""

    round_number: int = Field(..., description="1 for Round 1 (3 questions), 2 for Round 2 (2 questions).")
    questions: List[QuestionWithOptions] = Field(
        default_factory=list,
        description="Questions generated for this round.",
    )
    provider: str = Field(default="unknown", description="Which provider generated these questions.")