"""Base interfaces and shared validation for AI providers."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, List, Optional

from pydantic import BaseModel, ValidationError, field_validator


class ProviderError(Exception):
    """Base exception raised by provider integrations."""


class ProviderUnavailableError(ProviderError):
    """Raised when a provider cannot be reached or is misconfigured."""


class ProviderResponseError(ProviderError):
    """Raised when provider output cannot be validated."""


# ── Recommendation Plan Result ───────────────────────────────────────────────


class ProductTypeInfo(BaseModel):
    """A product type generated by AI (no product names, just functional class)."""
    product_type: str
    description: str


class RecommendationPlanResult(BaseModel):
    """Normalized recommendation plan result from AI providers."""

    category: str
    product_types: list[ProductTypeInfo]

    @field_validator("category")
    @classmethod
    def _validate_category(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("category cannot be empty")
        return cleaned

    @field_validator("product_types")
    @classmethod
    def _validate_product_types(cls, value: list[ProductTypeInfo]) -> list[ProductTypeInfo]:
        if not value:
            raise ValueError("must contain at least one product type")
        return value[:10]  # Enforce max 10


# ── Legacy CategoryReasoningResult (for backward compat during migration) ────


class RecommendedProductInfo(BaseModel):
    """Detailed info for a recommended product."""
    name: str
    explanation: str
    label: str


class CategoryReasoningResult(BaseModel):
    """Legacy category reasoning result — being replaced by RecommendationPlanResult."""

    categories: list[str]
    reasoning: str
    recommended_products: list[RecommendedProductInfo]

    @field_validator("categories")
    @classmethod
    def _validate_non_empty_list(cls, value: list[str]) -> list[str]:
        filtered = [item.strip() for item in value if item and item.strip()]
        if not filtered:
            raise ValueError("list must contain at least one non-empty value")
        return filtered

    @field_validator("recommended_products")
    @classmethod
    def _validate_non_empty_products(cls, value: list[RecommendedProductInfo]) -> list[RecommendedProductInfo]:
        if not value:
            raise ValueError("list must contain at least one recommended product")
        return value

    @field_validator("reasoning")
    @classmethod
    def _validate_reasoning(cls, value: str) -> str:
        cleaned = value.strip()
        if not cleaned:
            raise ValueError("reasoning cannot be empty")
        return cleaned


# ── Provider Abstract Base ───────────────────────────────────────────────────


class BaseCategoryProvider(ABC):
    """Interface for providers that can produce recommendation plan outputs."""

    provider_name: str

    @abstractmethod
    async def generate(
        self,
        *,
        query: str,
        context: list[dict[str, str]] | None = None,
        timeout_seconds: float = 8.0,
    ) -> CategoryReasoningResult:
        """Generate categories, reasoning, and recommended product names (legacy)."""

    async def generate_recommendation_plan(
        self,
        *,
        query: str,
        context: list[dict[str, str]] | None = None,
        user_profile: dict[str, Any] | None = None,
        timeout_seconds: float = 10.0,
    ) -> RecommendationPlanResult:
        """
        Generate recommendation plan per Flow.md Step 5.

        Default implementation falls back to legacy generate() and converts.
        Providers should override this with the new prompt.
        """
        legacy = await self.generate(query=query, context=context, timeout_seconds=timeout_seconds)
        return RecommendationPlanResult(
            category=legacy.categories[0] if legacy.categories else "Recommendations",
            product_types=[
                ProductTypeInfo(product_type=p.name, description=p.explanation)
                for p in legacy.recommended_products[:10]
            ],
        )


# ── Validation Utilities ─────────────────────────────────────────────────────


def parse_provider_payload(payload: Any) -> CategoryReasoningResult:
    """Validate and normalize provider output payloads (legacy format)."""
    if isinstance(payload, str):
        raise ProviderResponseError("Provider returned plain string instead of JSON payload")
    if not isinstance(payload, dict):
        raise ProviderResponseError(f"Provider returned unexpected payload type: {type(payload)!r}")

    try:
        return CategoryReasoningResult.model_validate(payload)
    except ValidationError as exc:
        raise ProviderResponseError(f"Provider payload validation failed: {exc}") from exc


def parse_recommendation_plan_payload(payload: Any) -> RecommendationPlanResult:
    """Validate and normalize recommendation plan payloads (new format)."""
    if isinstance(payload, str):
        raise ProviderResponseError("Provider returned plain string instead of JSON payload")
    if not isinstance(payload, dict):
        raise ProviderResponseError(f"Provider returned unexpected payload type: {type(payload)!r}")

    try:
        return RecommendationPlanResult.model_validate(payload)
    except ValidationError as exc:
        raise ProviderResponseError(f"Recommendation plan validation failed: {exc}") from exc
